### GENERAL SETTINGS ###

# Site settings
title: LinuxChix Argentina
description: "LinuxChix Argentina es una comunidad que busca conectar, visibilizar y fomentar la participación de mujeres en el software libre."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/linuxchixar-web"
url: "https://linuxchixar.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
   
# Redes sociales.
social:
  - title: facebook
    url: https://www.facebook.com/linuxchixar/
  - title: twitter
    url: https://www.twitter.com/linuxchixar/
  - title: meetup
    url: https://www.meetup.com/linuxchixar/events/236051124/ 
    
# Comunidades amigas.
communities:
  - name: Python Argentina
    img: pyar.png
  - name: Sysarmy
    img: sysarmy.png
  - name: Argentina en Python
    img: argentinaenpython.png
  - name: Chicas en Tecnología
    img: chicasentecnologia.jpg
    
# Texto corto (elevator pitch) sobre LinuxChix Argentina. Se muestra en el footer de todas las páginas.
about: "LinuxChix Argentina es una comunidad que busca conectar, visibilizar y fomentar la participación de mujeres en el software libre."

# Citas inspiracionles. Se muestra en el Inicio.
# TODO(vkmc). Agregar soporte para mas citas.
quotes:
    message: "Lo más difícil es la decisión de actuar, el resto es sólo tenacidad."
    author: Amelia Earhart
